// THIS FILE IS AUTOGENERATED BY THE BUILD PROCESS
// You can either set the keys in Variables.cmake or at the autobuild command
// For Exodus release builds the latter is *required* to maintain the
// secrecy of the API keys.

#define EXO_FLICKR_API_KEY "daaabff93a967e0f37fa18863bb43b29"
#define EXO_FLICKR_API_SECRET "846f0958020b553e"
